= Introduction
#v(1em)
High quality elevation data is increasingly available across Europe through national and regional mapping programmes. These datasets support a wide range of applications, including hydrological modelling, flood risk assessment, infrastructure planning, and environmental management. At the same time, many of these applications extend beyond administrative boundaries. The European INSPIRE framework therefore places emphasis on the interoperability of spatial datasets and on their consistent use across national borders. Elevation is one of the spatial data themes addressed within this framework @inspire2024elevation.

The Rhine catchment is a clear example of an area where cross border spatial information is important. The catchment covers approximately 200,000 km² and extends across several European countries, with around 60 million people living within the basin. The Rhine and its tributaries are important for water supply, navigation, industry, agriculture, ecosystems, and flood management. Management of the river basin is already coordinated internationally through organisations such as the International Commission for the Protection of the Rhine @icpr2022rhine. Many processes within the catchment, particularly water flow and flooding, depend directly on terrain. The quality and consistency of elevation data can therefore influence analyses performed at catchment scale @DEMhydrology.

Although detailed elevation datasets are available for large parts of Europe, they are generally collected and maintained by individual national or regional authorities. As a result, neighbouring datasets can differ in point density, spatial resolution, coordinate, and height reference systems, classification, and more. Recent work by EuroSDR has documented these differences across European point cloud datasets and has identified the absence of a harmonised cross border point cloud dataset at European scale @vanderheide2026pointcloud. Such differences create practical problems when elevation data from several jurisdictions needs to be combined into a single terrain model. Simply joining the available datasets does not necessarily result in a consistent representation of the terrain.

This forms the main problem addressed by this project. The aim is to investigate how elevation data covering the Rhine catchment can be processed into a harmonised Digital Elevation Model in an automated manner. The project considers the differences between the available source datasets and the processing steps required to bring them into a common representation. The exact geographic coverage, datasets, and harmonisation aspects considered within the project are defined further through the research questions and subquestions.

// This Project Initiation Document defines the approach that will be used to carry out the project. It establishes the research questions, scope, methodology, required data, planning, and expected outcomes. The following sections describe these elements in more detail and provide the basis for the execution and evaluation of the project.

This Project Initiation Document defines the approach that will be used to carry out the project. Chapter 2 will discuss the contributors of the project. It briefly goes into the team members, supervisors and the client. Chapter 3 goes into the project definition, consisting of research questions, relevant courses and requirements. Chapter 4 discusses the methodology used for the project which goes into the research approach, pipeline design and quality assurance. Lastly, chapter 5 discusses the planning, communication and risk analysis of the project.